(fix) use /usr/bin/env in shebang for all scripts

diff --git a/bin/ini_parser b/bin/ini_parser
--- a/bin/ini_parser
+++ b/bin/ini_parser
@@ -1,5 +1,5 @@
-#!/bin/bash
-#
+#!/usr/bin/env bash
+
 # Copyright 2015 Olivier van Helden <olivier@van-helden.net>
 # Released under GNU Affero GPL v3.0 license
 #    http://www.gnu.org/licenses/agpl-3.0.html
@@ -47,190 +47,178 @@ TMPINI=$TMP.ini_parser
 
 trap "{ rm -f $TMPINI.*; ls $TMPINI.* 2>/dev/null; }" EXIT
 
-ini.cat ()
-{
-    cat $@ \
-	| egrep -v "^[[:blank:]]*$|^[[:blank:]]*;" \
-	| sed "s/^[[:blank:]]*//" \
-	| sed "s/[[:blank:]]*$//" \
-	| sed ':a;N;$!ba;s/\[[[:alpha:]]*\]\n\[/[/g' \
-	| sed "s/[[:blank:]]*=[[:blank:]]*/=/g" \
-	| sed "s/^[[:blank:]]*;.*//" \
-	| sed "s/;[[:blank:]]*$//" \
-	| sed "s/^[[:blank:]]*$//"
+ini.cat() {
+	cat $@ |
+		egrep -v "^[[:blank:]]*$|^[[:blank:]]*;" |
+		sed "s/^[[:blank:]]*//" |
+		sed "s/[[:blank:]]*$//" |
+		sed ':a;N;$!ba;s/\[[[:alpha:]]*\]\n\[/[/g' |
+		sed "s/[[:blank:]]*=[[:blank:]]*/=/g" |
+		sed "s/^[[:blank:]]*;.*//" |
+		sed "s/;[[:blank:]]*$//" |
+		sed "s/^[[:blank:]]*$//"
 }
-ini.parse ()
-{
-  [ ! "$1" ] && log 1 "usage: $FUNCNAME <file.ini>" && return 1
-  [ ! -f "$1" ] && log 1 "usage: $FUNCNAME <file.ini>" && return 1
-    SAVED_IFS=$IFS
-    # ini="$(<$1)"                # read the file
-    ini=$(
-	ini.cat $@ \
-	    | sed "s/;/%%SEMICOLON%%/g" \
-	    | sed "s/\([{\\$]\)/\\\\\1/g" \
-	    | sed "s/=\([^\"].*[|{}\\$].*\)\"*$/=\"\\1\"/g" \
-	    | sed "s/=/%3D/g" \
-	    | sed "s/%3D/=/"
-    )
-    ini="${ini//[/\[}"          # escape [
-    ini="${ini//]/\]}"          # escape ]
-    IFS=$'\n' && ini=( ${ini} ) # convert to line-array
-    ini=( ${ini[*]//;*/} )      # remove comments with ;
-    ini=( ${ini[*]/\    =/=} )  # remove tabs before =
-    ini=( ${ini[*]/=\   /=} )   # remove tabs after =
-    ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
-    ini=( ${ini[*]/#\\[/\}$'\n'ini.section.} ) # set section prefix
-    ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
-    ini=( ${ini[*]/=/=\(} )    # convert item to array
-    ini=( ${ini[*]/%/ \)} )     # close array parenthesis
-    ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
-    ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
-    ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
-    ini[0]="" # remove first element
-    ini[${#ini[*]} + 1]='}'    # add the last brace
-    eval "$(echo "${ini[*]}" \
-            | sed -e 's/\\$\\{/\\\${/g' \
-              -e 's/%%SEMICOLON%%/;/g' \
-              -e 's/%3B/;/g' \
-              -e 's/%3D/=/g'
-           )"
-    exitcode=$?
-    ini_cache=$@
-    ini_parsed=$@
-    IFS=$OLDIFS
-    return $exitcode
-}
-
-ini.list.sections ()
-{
-  [ ! "$1" -a ! "$ini_parsed" ] && end 1 "$FUNCNAME needs you to load one or more .ini before using $FUNCNAME or supply files to load to the command"
-
-  if [ "$1" ]
-  then
-    ini_process=$@
-  else
-    ini_process=$ini_parsed
-  fi
-  printf "" > $TMPINI.sections
-  IFS=" "
-  i=0
-  touch $TMPINI.sections
-  for file in $ini_process
-  do
-    [ ! -f "$file" ] && log 1 "$FUNCNAME $file not found" && continue
-    touch $TMPINI.sections.new $TMPINI.sections.added
-    i=$(($i + 1))
-    printf "" | ini.cat $file \
-    | grep "^[[:blank:]]*\[[a-zA-Z0-9_]*\]" \
-    | cut -d "[" -f 2 | cut -d "]" -f 1 \
-    | while read section
-    do
-      grep -q "^$section$" $TMPINI.sections \
-      && continue
-      grep -q "^$section$" $TMPINI.sections.added \
-      && continue
-      echo $section >> $TMPINI.sections.added
-    done
-    cat  $TMPINI.sections $TMPINI.sections.added > $TMPINI.sections.new 2>/dev/null
-    mv $TMPINI.sections.new $TMPINI.sections
-    rm -f $TMPINI.sections.added
-  done
-  cat $TMPINI.sections
-  rm -f $TMPINI.sections
-  return
+ini.parse() {
+	[ ! "$1" ] && log 1 "usage: $FUNCNAME <file.ini>" && return 1
+	[ ! -f "$1" ] && log 1 "usage: $FUNCNAME <file.ini>" && return 1
+	SAVED_IFS=$IFS
+	# ini="$(<$1)"                # read the file
+	ini=$(
+		ini.cat $@ |
+			sed "s/;/%%SEMICOLON%%/g" |
+			sed "s/\([{\\$]\)/\\\\\1/g" |
+			sed "s/=\([^\"].*[|{}\\$].*\)\"*$/=\"\\1\"/g" |
+			sed "s/=/%3D/g" |
+			sed "s/%3D/=/"
+	)
+	ini="${ini//[/\[}"                       # escape [
+	ini="${ini//]/\]}"                       # escape ]
+	IFS=$'\n' && ini=(${ini})                # convert to line-array
+	ini=(${ini[*]//;*/})                     # remove comments with ;
+	ini=(${ini[*]/\    =/=})                 # remove tabs before =
+	ini=(${ini[*]/=\   /=})                  # remove tabs after =
+	ini=(${ini[*]/\ =\ /=})                  # remove anything with a space around =
+	ini=(${ini[*]/#\\[/\}$'\n'ini.section.}) # set section prefix
+	ini=(${ini[*]/%\\]/ \(})                 # convert text2function (1)
+	ini=(${ini[*]/=/=\(})                    # convert item to array
+	ini=(${ini[*]/%/ \)})                    # close array parenthesis
+	ini=(${ini[*]/%\\ \)/ \\})               # the multiline trick
+	ini=(${ini[*]/%\( \)/\(\) \{})           # convert text2function (2)
+	ini=(${ini[*]/%\} \)/\}})                # remove extra parenthesis
+	ini[0]=""                                # remove first element
+	ini[${#ini[*]} + 1]='}'                  # add the last brace
+	eval "$(
+		echo "${ini[*]}" |
+			sed -e 's/\\$\\{/\\\${/g' \
+				-e 's/%%SEMICOLON%%/;/g' \
+				-e 's/%3B/;/g' \
+				-e 's/%3D/=/g'
+	)"
+	exitcode=$?
+	ini_cache=$@
+	ini_parsed=$@
+	IFS=$OLDIFS
+	return $exitcode
 }
 
-ini.write ()
-{
-    [ "$1" = "-a" ] && APPEND=yes && shift || unset APPEND
-    SAVED_IFS=$IFS
-    IFS=' '$'\n'
-    fun="$(declare -F)"
-    fun="${fun//declare -f/}"
-    for f in $fun; do
-        [ "${f#ini.section}" == "${f}" ] && continue
-	[ "$1" ] && [ "$f" != "ini.section.$1" ] && continue
-#        item="$(declare -f ${f})"
-        item="$(declare -f ${f} | sed -e 's/\\${.*}/BRACE/g' -e "s/=/%3D/g" -e "s/%3D/=/")"
-        item="${item##*[^\\]\{}"
-        item="${item%\}}"
-#        item="${item//=*;/}"
-#        vars="${item//=*/}"
- 	vars="$item"
-        [ ! "$APPEND" ] && echo "[${f#ini.section.}]"
-	for var in $vars; do
-	    echo "$var" | grep -q "=" || continue
-	    var=$(echo $var | sed -e "s/=/%3D/g" -e "s/%3D/=/")
-	    var="${var%=*}"
-            echo "$TAB"$var=\"${!var}\" | grep -v ');*=""'
-        done | sed 's/${/$\\{/g' > $TMPINI.vars
-	eval $f
-	. $TMPINI.vars
-	rm -f $TMPINI.vars
-        for var in $vars; do
-	    echo "$var" | grep -q "=" || continue
-	    var="${var%=*}"
-            echo "$TAB"$var = \"${!var}\" | grep -v ');*=""'
-        done | sed "s/\$\\\{/$\{/"
-    done
-    IFS=$SAVED_IFS
+ini.list.sections() {
+	[ ! "$1" -a ! "$ini_parsed" ] && end 1 "$FUNCNAME needs you to load one or more .ini before using $FUNCNAME or supply files to load to the command"
+
+	if [ "$1" ]; then
+		ini_process=$@
+	else
+		ini_process=$ini_parsed
+	fi
+	printf "" >$TMPINI.sections
+	IFS=" "
+	i=0
+	touch $TMPINI.sections
+	for file in $ini_process; do
+		[ ! -f "$file" ] && log 1 "$FUNCNAME $file not found" && continue
+		touch $TMPINI.sections.new $TMPINI.sections.added
+		i=$(($i + 1))
+		printf "" | ini.cat $file |
+			grep "^[[:blank:]]*\[[a-zA-Z0-9_]*\]" |
+			cut -d "[" -f 2 | cut -d "]" -f 1 |
+			while read section; do
+				grep -q "^$section$" $TMPINI.sections &&
+					continue
+				grep -q "^$section$" $TMPINI.sections.added &&
+					continue
+				echo $section >>$TMPINI.sections.added
+			done
+		cat $TMPINI.sections $TMPINI.sections.added >$TMPINI.sections.new 2>/dev/null
+		mv $TMPINI.sections.new $TMPINI.sections
+		rm -f $TMPINI.sections.added
+	done
+	cat $TMPINI.sections
+	rm -f $TMPINI.sections
+	return
 }
 
-ini.merge()
-{
-  [ ! "$2" ] && log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]" && return 1
-  section=$1; shift
-  ini.list.sections $@ | grep -q "^$section$"
-  if [ $? -ne 0 ]
-  then
-    log 1 "$FUNCNAME didn't find the section $section"
-    log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]"
-    return 1
-  fi
-
-  echo "[$section]" > $TMPINI.merge
-  i=0
-  for file in $@
-  do
-    i=$(($i + 1))
-    #	touch $TMPINI.merge.$i
-    [ ! -f "$file" ] && continue
-
-    ini.parse $file 2>/dev/null
-    ini.list.sections $file | grep -q "^$section$" || continue
-    ini.section.$section || continue
-    ini.write -a $section | while read line
-    do
-      var=$(echo "$line" | cut -d = -f 1 \
-      | sed "s/[[:blank:]]*//g")
-      egrep -v "^[[:blank:]]*$var[[:blank:]]*=" $TMPINI.merge > $TMPINI.merge.new
-      echo "$line" >> $TMPINI.merge.new
-      mv $TMPINI.merge.new $TMPINI.merge
-    done
-  done
-  count=$(cat $TMPINI.merge | wc -l)
-  [ $count -gt 1 ] &&
-  ini.parse $TMPINI.merge && ini_parsed="$@"*
-  rm -f $TMPINI.merge.*
-  return
+ini.write() {
+	[ "$1" = "-a" ] && APPEND=yes && shift || unset APPEND
+	SAVED_IFS=$IFS
+	IFS=' '$'\n'
+	fun="$(declare -F)"
+	fun="${fun//declare -f/}"
+	for f in $fun; do
+		[ "${f#ini.section}" == "${f}" ] && continue
+		[ "$1" ] && [ "$f" != "ini.section.$1" ] && continue
+		#        item="$(declare -f ${f})"
+		item="$(declare -f ${f} | sed -e 's/\\${.*}/BRACE/g' -e "s/=/%3D/g" -e "s/%3D/=/")"
+		item="${item##*[^\\]\{}"
+		item="${item%\}}"
+		#        item="${item//=*;/}"
+		#        vars="${item//=*/}"
+		vars="$item"
+		[ ! "$APPEND" ] && echo "[${f#ini.section.}]"
+		for var in $vars; do
+			echo "$var" | grep -q "=" || continue
+			var=$(echo $var | sed -e "s/=/%3D/g" -e "s/%3D/=/")
+			var="${var%=*}"
+			echo "$TAB"$var=\"${!var}\" | grep -v ');*=""'
+		done | sed 's/${/$\\{/g' >$TMPINI.vars
+		eval $f
+		. $TMPINI.vars
+		rm -f $TMPINI.vars
+		for var in $vars; do
+			echo "$var" | grep -q "=" || continue
+			var="${var%=*}"
+			echo "$TAB"$var = \"${!var}\" | grep -v ');*=""'
+		done | sed "s/\$\\\{/$\{/"
+	done
+	IFS=$SAVED_IFS
 }
 
-ini.write.all ()
-{
-  [ ! "$1" ] && [ ! "$ini_parsed" ] && log 1 "$FUNCNAME needs you to load one or more .ini before using write.all or supply files to load to the command" && return 1
-  if [ "$1" -a "$1" != "$ini_parsed" ]
-  then
-    ini.parse $@
-    ini.write.all
-     # $@
-    return
-  fi
+ini.merge() {
+	[ ! "$2" ] && log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]" && return 1
+	section=$1
+	shift
+	ini.list.sections $@ | grep -q "^$section$"
+	if [ $? -ne 0 ]; then
+		log 1 "$FUNCNAME didn't find the section $section"
+		log 1 "Usage: $FUNCNAME Section <file1.ini> [<file2.ini>] [...]"
+		return 1
+	fi
 
-  ini.list.sections $ini_parsed | while read section
-  do
-    ini.merge $section $ini_parsed
-    ini.section.$section 2>/dev/null
-    ini.write $section
-  done
+	echo "[$section]" >$TMPINI.merge
+	i=0
+	for file in $@; do
+		i=$(($i + 1))
+		#	touch $TMPINI.merge.$i
+		[ ! -f "$file" ] && continue
+
+		ini.parse $file 2>/dev/null
+		ini.list.sections $file | grep -q "^$section$" || continue
+		ini.section.$section || continue
+		ini.write -a $section | while read line; do
+			var=$(echo "$line" | cut -d = -f 1 |
+				sed "s/[[:blank:]]*//g")
+			egrep -v "^[[:blank:]]*$var[[:blank:]]*=" $TMPINI.merge >$TMPINI.merge.new
+			echo "$line" >>$TMPINI.merge.new
+			mv $TMPINI.merge.new $TMPINI.merge
+		done
+	done
+	count=$(cat $TMPINI.merge | wc -l)
+	[ $count -gt 1 ] &&
+		ini.parse $TMPINI.merge && ini_parsed="$@"*
+	rm -f $TMPINI.merge.*
+	return
+}
+
+ini.write.all() {
+	[ ! "$1" ] && [ ! "$ini_parsed" ] && log 1 "$FUNCNAME needs you to load one or more .ini before using write.all or supply files to load to the command" && return 1
+	if [ "$1" -a "$1" != "$ini_parsed" ]; then
+		ini.parse $@
+		ini.write.all
+		# $@
+		return
+	fi
+
+	ini.list.sections $ini_parsed | while read section; do
+		ini.merge $section $ini_parsed
+		ini.section.$section 2>/dev/null
+		ini.write $section
+	done
 }
diff --git a/bin/mail-report b/bin/mail-report
--- a/bin/mail-report
+++ b/bin/mail-report
@@ -1,112 +1,107 @@
-#!/bin/sh
-#
+#!/usr/bin/env bash
+
 # Copyright 2015 Olivier van Helden <olivier@van-helden.net>
 # Released under GNU Affero GPL v3.0 license
 #    http://www.gnu.org/licenses/agpl-3.0.html
 
 PID=$$
-PGM=`basename $0`
+PGM=$(basename $0)
 TMP=/tmp/.$PGM.$PID
 BILLDETAIL=/tmp/$PGM-billdetail
 LOG=/tmp/$PGM
-TABLE=`echo "tmp_${PGM}_${PID}" | sed "s/[^a-zA-Z0-9_]//g"`
+TABLE=$(echo "tmp_${PGM}_${PID}" | sed "s/[^a-zA-Z0-9_]//g")
 
 export PAGER=cat
 
 OPTS="b:c:s:r:hvq"
 
-PAR=`echo $OPTS|sed 's/.://g'|grep -v "^$"|sed "s/\([a-zA-Z0-9]*\)/[-\\1]/g" `
-PAROPT=`echo $OPTS | sed "s/-://" | sed 's/\(.\)/\\1\//g' \
-    | sed 's/\(.\)\/:\//[-\\1 <value>] /g' \
-    | sed "s/.\///g" `
-USAGE=`echo $PGM $PAR $PAROPT "[<args>]" | sed "s/  / /g"`
-
+PAR=$(echo $OPTS | sed 's/.://g' | grep -v "^$" | sed "s/\([a-zA-Z0-9]*\)/[-\1]/g")
+PAROPT=$(echo $OPTS | sed "s/-://" | sed 's/\(.\)/\1\//g' |
+	sed 's/\(.\)\/:\//[-\1 <value>] /g' |
+	sed "s/.\///g")
+USAGE=$(echo $PGM $PAR $PAROPT "[<args>]" | sed "s/  / /g")
 
 help() {
-    usage
-    echo
-    echo "      -t <template>"
-    echo "      -H display this help"
-    echo "      -V verbose mode"
-    echo "      -Q quiet mode"
-    echo
-    echo "sorry, helpman is in a minimalist mood"
-    exit 0
+	usage
+	echo
+	echo "      -t <template>"
+	echo "      -H display this help"
+	echo "      -V verbose mode"
+	echo "      -Q quiet mode"
+	echo
+	echo "sorry, helpman is in a minimalist mood"
+	exit 0
 }
 
 usage() {
-    echo "usage: $USAGE"
+	echo "usage: $USAGE"
 }
 
 log() {
-    if [ "$LOG" ]
-        then
-        ERRNUM=`echo "$@" |grep "^[0-9]* "|cut -d " " -f 1`
-        ERR=`echo $ERRNUM|sed "s/\([0-9]*\)/<\\1\> /"`
-        [ "$ERRNUM" ] && shift
-        LOGMESSAGE=$@
-        LOGLINE=`date +"%b %e %H:%M:%S"`" $PGM[$$]: $ERR$LOGMESSAGE"
-        [ "$LOGGING" = "yes" ] && (echo $LOGLINE >> $LOG.log)
-        if [ "$ERRNUM" -a "$QUIET" != "yes" ]
-            then
-            echo "$PGM: $LOGMESSAGE ($ERRNUM)" >&2
-        elif [ "$DEBUG" = "yes" ]
-            then
-            echo "$PGM: $LOGMESSAGE" >&2
-        fi
-    else
-        echo "LOG variable not set"
-        exit 1
-    fi
+	if [ "$LOG" ]; then
+		ERRNUM=$(echo "$@" | grep "^[0-9]* " | cut -d " " -f 1)
+		ERR=$(echo $ERRNUM | sed "s/\([0-9]*\)/<\1\> /")
+		[ "$ERRNUM" ] && shift
+		LOGMESSAGE=$@
+		LOGLINE=$(date +"%b %e %H:%M:%S")" $PGM[$$]: $ERR$LOGMESSAGE"
+		[ "$LOGGING" = "yes" ] && (echo $LOGLINE >>$LOG.log)
+		if [ "$ERRNUM" -a "$QUIET" != "yes" ]; then
+			echo "$PGM: $LOGMESSAGE ($ERRNUM)" >&2
+		elif [ "$DEBUG" = "yes" ]; then
+			echo "$PGM: $LOGMESSAGE" >&2
+		fi
+	else
+		echo "LOG variable not set"
+		exit 1
+	fi
 }
 
 end() {
-#    ERRNUM=$1
-#    if [ "$ERRNUM" != "" -a "$ERRNUM" = "`echo $ERRNUM|sed 's/[^0-9]//g'`" ]
-#        then
-#        ERRNUM=`expr $ERRNUM + 0`
-#        shift
-#        [ "$#" -gt 0 ]  && log "<$ERRNUM>" $@
-#    else
-#        ERRNUM=
-#        if [ "$#" -gt 0 ]
-#            then
-#            log $@
-#	elif [ "$DEBUG" = "yes" ]
-#	    then
-	if [ "$1" ]
-		then
+	#    ERRNUM=$1
+	#    if [ "$ERRNUM" != "" -a "$ERRNUM" = "`echo $ERRNUM|sed 's/[^0-9]//g'`" ]
+	#        then
+	#        ERRNUM=`expr $ERRNUM + 0`
+	#        shift
+	#        [ "$#" -gt 0 ]  && log "<$ERRNUM>" $@
+	#    else
+	#        ERRNUM=
+	#        if [ "$#" -gt 0 ]
+	#            then
+	#            log $@
+	#	elif [ "$DEBUG" = "yes" ]
+	#	    then
+	if [ "$1" ]; then
 		log $@
 	else
-	    log "End processing"
-    fi
-    rm -f $TMP*
-    rm -f $LOG.lock
-    exit $ERRNUM
+		log "End processing"
+	fi
+	rm -f $TMP*
+	rm -f $LOG.lock
+	exit $ERRNUM
 }
 
-while getopts $OPTS PARAM
-  do
-    case $PARAM in
+while getopts $OPTS PARAM; do
+	case $PARAM in
 	"?")
-	    ERROR=1
-	    ;;
+		ERROR=1
+		;;
 	-)
-	    case $OPTARG in
+		case $OPTARG in
 		help)
-		    help
-		    ;;
+			help
+			;;
 		*)
-		    printf "$PGM: illegal option -- $OPTARG"
-#		    ERROR=1
-	    esac
-	    ;;
+			printf "$PGM: illegal option -- $OPTARG"
+			#		    ERROR=1
+			;;
+		esac
+		;;
 	r)
-	    FROM=$OPTARG
-	    ;;
+		FROM=$OPTARG
+		;;
 	s)
-	    SUBJECT=$OPTARG
-	    ;;
+		SUBJECT=$OPTARG
+		;;
 	c)
 		CC=$OPTARG
 		;;
@@ -114,58 +109,53 @@ while getopts $OPTS PARAM
 		BCC=$OPTARG
 		;;
 	H)
-	    help
-	    ;;
+		help
+		;;
 	V)
-#		    echo "Debug mode"
-	    STDERR="&1"
-	    DEBUG=yes
-	    ;;
+		#		    echo "Debug mode"
+		STDERR="&1"
+		DEBUG=yes
+		;;
 	Q)
-	    STDOUT="/dev/null"
+		STDOUT="/dev/null"
 		QUIET=yes
-	    DEBUG=no
-	            ;;
+		DEBUG=no
+		;;
 	*)
-	    VALUES="$VALUES $PARAM"
-	    LASTVAL=$PARAM
-    esac
+		VALUES="$VALUES $PARAM"
+		LASTVAL=$PARAM
+		;;
+	esac
 
 done 2>/dev/null
 
-shift `expr $OPTIND - 1`
+shift $(expr $OPTIND - 1)
 
-if [ $ERROR ]
-then
-    usage
-echo "$ERROR   type '$PGM --help' for more info"
+if [ $ERROR ]; then
+	usage
+	echo "$ERROR   type '$PGM --help' for more info"
 
-    end "$ERROR   type '$PGM --help' for more info"
+	end "$ERROR   type '$PGM --help' for more info"
 fi
 
-if [ ! "$USER" ]
-then
-	USER=`id|cut -d "(" -f 2|cut -d ")" -f 1`
+if [ ! "$USER" ]; then
+	USER=$(id | cut -d "(" -f 2 | cut -d ")" -f 1)
 fi
 
-if [ ! "$HOSTNAME" ]
-then
-	HOSTNAME=`hostname`
+if [ ! "$HOSTNAME" ]; then
+	HOSTNAME=$(hostname)
 fi
 
-if [ ! "$DOMAINNAME" ]
-then
-	DOMAINNAME=`domainname`
-	if [ ! "$DOMAINNAME" -o "$DOMAINNAME" = "(none)" ];
-	then
+if [ ! "$DOMAINNAME" ]; then
+	DOMAINNAME=$(domainname)
+	if [ ! "$DOMAINNAME" -o "$DOMAINNAME" = "(none)" ]; then
 		DOMAINNAME=magiiic.com
 	fi
 fi
 
 RETMAIL="$HOSTNAME@$DOMAINNAME"
 
-if [ -f "$FROM" ]
-	then
+if [ -f "$FROM" ]; then
 	SENDER=$FROM
 else
 	SENDER="\"$HOSTNAME\" <$RETMAIL>"
@@ -183,7 +173,7 @@ fi
 #  TRSUB=$TRDIR/.trace_ftp_mail.$$.4t
 #  INPUT=$TRDIR/.input_ftp_mail.$$.t
 
-DEST=`echo $@|sed "s/ /,/g"|sed "s/,,*/,/g"` 
+DEST=$(echo $@ | sed "s/ /,/g" | sed "s/,,*/,/g")
 
 #  cat > $INPUT
 #  echo "$SUB" > $TRSUB
@@ -193,29 +183,26 @@ DEST=`echo $@|sed "s/ /,/g"|sed "s/,,*/,/g"`
 #  cat $INPUT >> $TRSUB
 
 parentpid=$PPID
-parentcmd=`ps -p $$ -o command=`
-parentusr=`ps -p $$ -o user=`
+parentcmd=$(ps -p $$ -o command=)
+parentusr=$(ps -p $$ -o user=)
 
-
-if [ "$SUBJECT" = "" ]
-	then
+if [ "$SUBJECT" = "" ]; then
 	SUBJECT="$parentcmd report"
 fi
 
-if [ "$DEST" = "" ]
-	then
+if [ "$DEST" = "" ]; then
 	DEST="report@$DOMAINNAME"
 fi
 
-echo "From: $SENDER" > $TMP.headers
-echo "Reply-To: $SENDER" > $TMP.headers
-echo "To: $DEST" >> $TMP.headers
-[ "$CC" ]  && echo "Cc: $CC"   >> $TMP.headers
-[ "$BCC" ] && echo "Bcc: $BCC" >> $TMP.headers
-echo "Subject: $SUBJECT" >> $TMP.headers
-echo "X-PPID: $PPID" >> $TMP.headers
-echo "X-Parent-Process: $parentcmd" >> $TMP.headers
-echo "X-Parent-User: $parentusr" >> $TMP.headers
+echo "From: $SENDER" >$TMP.headers
+echo "Reply-To: $SENDER" >$TMP.headers
+echo "To: $DEST" >>$TMP.headers
+[ "$CC" ] && echo "Cc: $CC" >>$TMP.headers
+[ "$BCC" ] && echo "Bcc: $BCC" >>$TMP.headers
+echo "Subject: $SUBJECT" >>$TMP.headers
+echo "X-PPID: $PPID" >>$TMP.headers
+echo "X-Parent-Process: $parentcmd" >>$TMP.headers
+echo "X-Parent-User: $parentusr" >>$TMP.headers
 
 # ps -ef|grep $$ \
 #     | while read user pid ppid foo date term time command
@@ -228,8 +215,7 @@ echo "X-Parent-User: $parentusr" >> $TMP.headers
 #   fi
 # done
 
-
-# if [  -f $TMP ] 
+# if [  -f $TMP ]
 #     then
 #     . $TMP
 #     ps -ef|grep $X_PPID \
@@ -243,18 +229,17 @@ echo "X-Parent-User: $parentusr" >> $TMP.headers
 #     done
 # fi
 
-cat > $TMP.input
+cat >$TMP.input
 grep -q . $TMP.input
-if [ $? -ne 0 ]
-then
-    rm -f $TMP.*
-    exit 0
+if [ $? -ne 0 ]; then
+	rm -f $TMP.*
+	exit 0
 fi
 
-grep -q "<[a-zA-Z].*>" $TMP.input \
-    && echo "Content-Type: text/html" >> $TMP.headers \
-    || echo "Content-Type: text/plain" >> $TMP.headers
-echo >> $TMP.headers
+grep -q "<[a-zA-Z].*>" $TMP.input &&
+	echo "Content-Type: text/html" >>$TMP.headers ||
+	echo "Content-Type: text/plain" >>$TMP.headers
+echo >>$TMP.headers
 
 cat $TMP.headers $TMP.input | /usr/sbin/sendmail "$DEST"
 
diff --git a/bin/tildelete b/bin/tildelete
--- a/bin/tildelete
+++ b/bin/tildelete
@@ -1,146 +1,138 @@
-#!/bin/sh
-#
+#!/usr/bin/env bash
+
 # Copyright 2015 Olivier van Helden <olivier@van-helden.net>
 # Released under GNU Affero GPL v3.0 license
 #    http://www.gnu.org/licenses/agpl-3.0.html
 
 PID=$$
-PGM=`basename $0`
+PGM=$(basename $0)
 TMP=/tmp/.$PGM.$PID
 BILLDETAIL=/tmp/$PGM-billdetail
 LOG=/tmp/$PGM
-TABLE=`echo "tmp_${PGM}_${PID}" | sed "s/[^a-zA-Z0-9_]//g"`
+TABLE=$(echo "tmp_${PGM}_${PID}" | sed "s/[^a-zA-Z0-9_]//g")
 
 export PAGER=cat
 
 OPTS="dHVQ"
 
-PAR=`echo $OPTS|sed 's/.://g'|grep -v "^$"|sed "s/\([a-zA-Z0-9]*\)/[-\\1]/g" `
-PAROPT=`echo $OPTS | sed "s/-://" | sed 's/\(.\)/\\1\//g' \
-    | sed 's/\(.\)\/:\//[-\\1 <value>] /g' \
-    | sed "s/.\///g" `
-USAGE=`echo $PGM $PAR $PAROPT "[<args>]" | sed "s/  / /g"`
-
+PAR=$(echo $OPTS | sed 's/.://g' | grep -v "^$" | sed "s/\([a-zA-Z0-9]*\)/[-\1]/g")
+PAROPT=$(echo $OPTS | sed "s/-://" | sed 's/\(.\)/\1\//g' |
+	sed 's/\(.\)\/:\//[-\1 <value>] /g' |
+	sed "s/.\///g")
+USAGE=$(echo $PGM $PAR $PAROPT "[<args>]" | sed "s/  / /g")
 
 help() {
-    usage
-    echo
-    echo "      -t <template>"
-    echo "      -H display this help"
-    echo "      -V verbose mode"
-    echo "      -Q quiet mode"
-    echo
-    echo "sorry, helpman is in a minimalist mood"
-    exit 0
+	usage
+	echo
+	echo "      -t <template>"
+	echo "      -H display this help"
+	echo "      -V verbose mode"
+	echo "      -Q quiet mode"
+	echo
+	echo "sorry, helpman is in a minimalist mood"
+	exit 0
 }
 
 usage() {
-    echo "usage: $USAGE"
+	echo "usage: $USAGE"
 }
 
 log() {
-    if [ "$LOG" ]
-        then
-        ERRNUM=`echo "$@" |grep "^[0-9]* "|cut -d " " -f 1`
-        ERR=`echo $ERRNUM|sed "s/\([0-9]*\)/<\\1\> /"`
-        [ "$ERRNUM" ] && shift
-        LOGMESSAGE=$@
-        LOGLINE=`date +"%b %e %H:%M:%S"`" $PGM[$$]: $ERR$LOGMESSAGE"
-        [ "$LOGGING" = "yes" ] && (echo $LOGLINE >> $LOG.log)
-        if [ "$ERRNUM" -a "$QUIET" != "yes" ]
-            then
-            echo "$PGM: $LOGMESSAGE ($ERRNUM)" >&2
-        elif [ "$DEBUG" = "yes" ]
-            then
-            echo "$PGM: $LOGMESSAGE" >&2
-        fi
-    else
-        echo "LOG variable not set"
-        exit 1
-    fi
+	if [ "$LOG" ]; then
+		ERRNUM=$(echo "$@" | grep "^[0-9]* " | cut -d " " -f 1)
+		ERR=$(echo $ERRNUM | sed "s/\([0-9]*\)/<\1\> /")
+		[ "$ERRNUM" ] && shift
+		LOGMESSAGE=$@
+		LOGLINE=$(date +"%b %e %H:%M:%S")" $PGM[$$]: $ERR$LOGMESSAGE"
+		[ "$LOGGING" = "yes" ] && (echo $LOGLINE >>$LOG.log)
+		if [ "$ERRNUM" -a "$QUIET" != "yes" ]; then
+			echo "$PGM: $LOGMESSAGE ($ERRNUM)" >&2
+		elif [ "$DEBUG" = "yes" ]; then
+			echo "$PGM: $LOGMESSAGE" >&2
+		fi
+	else
+		echo "LOG variable not set"
+		exit 1
+	fi
 }
 
 end() {
-    if [ "$1" ]
-	then
-	log $@
-    else
-	log "End processing"
-    fi
-    rm -f $TMP*
-    rm -f $LOG.lock
-    exit $ERRNUM
+	if [ "$1" ]; then
+		log $@
+	else
+		log "End processing"
+	fi
+	rm -f $TMP*
+	rm -f $LOG.lock
+	exit $ERRNUM
 }
 
-while getopts $OPTS PARAM
-  do
-    case $PARAM in
+while getopts $OPTS PARAM; do
+	case $PARAM in
 	"?")
-	    ERROR=1
-	    ;;
+		ERROR=1
+		;;
 	-)
-	    case $OPTARG in
+		case $OPTARG in
 		help)
-		    help
-		    ;;
+			help
+			;;
 		*)
-		    printf "$PGM: illegal option -- $OPTARG"
-#		    ERROR=1
-	    esac
-	    ;;
+			printf "$PGM: illegal option -- $OPTARG"
+			#		    ERROR=1
+			;;
+		esac
+		;;
 	d)
-	    DOIT=true
-	    ;;
-#	t)
-#	    printf "$PARAM set to $OPTARG\n"
-#	    TEMPLATE=$OPTARG
-#	    ;;
+		DOIT=true
+		;;
+		#	t)
+		#	    printf "$PARAM set to $OPTARG\n"
+		#	    TEMPLATE=$OPTARG
+		#	    ;;
 	H)
-	    help
-	    ;;
+		help
+		;;
 	V)
-#		    echo "Debug mode"
-	    STDERR="&1"
-	    DEBUG=yes
-	    ;;
+		#		    echo "Debug mode"
+		STDERR="&1"
+		DEBUG=yes
+		;;
 	Q)
-	    STDOUT="/dev/null"
+		STDOUT="/dev/null"
 		QUIET=yes
-	    DEBUG=no
-	            ;;
+		DEBUG=no
+		;;
 	*)
-	    VALUES="$VALUES $PARAM"
-	    LASTVAL=$PARAM
-    esac
+		VALUES="$VALUES $PARAM"
+		LASTVAL=$PARAM
+		;;
+	esac
 
 done 2>/dev/null
 
-shift `expr $OPTIND - 1`
+shift $(expr $OPTIND - 1)
 
-if [ $ERROR ]
-    then
-    usage
-    echo "$ERROR   type '$PGM --help' for more info"
-    end "$ERROR   type '$PGM --help' for more info"
+if [ $ERROR ]; then
+	usage
+	echo "$ERROR   type '$PGM --help' for more info"
+	end "$ERROR   type '$PGM --help' for more info"
 fi
 
-if [ ! "$1" ]
-    then
-    find . -type f -name "*~" >> $TMP.files
+if [ ! "$1" ]; then
+	find . -type f -name "*~" >>$TMP.files
 else
-    while [ "$1" ]
-      do
-      find "$1" -type f -name "*~" >> $TMP.files
-      shift
-    done
+	while [ "$1" ]; do
+		find "$1" -type f -name "*~" >>$TMP.files
+		shift
+	done
 fi
-  
-if [ "$DOIT" = true ]
-    then
-    cat $TMP.files | sed "s/\(.*\)/\"\\1\"/" | xargs  rm 
-    end
+
+if [ "$DOIT" = true ]; then
+	cat $TMP.files | sed "s/\(.*\)/\"\\1\"/" | xargs rm
+	end
 else
-    cat $TMP.files | sed "s/\(.*\)/\"\\1\"/" 
+	cat $TMP.files | sed "s/\(.*\)/\"\\1\"/"
 fi
 
 #| xargs rm
